In [26]:
import os

print(os.getcwd())

d:\downloads\Documents\Retail-Sales-Analytics\notebooks

In [27]:
import os

print(os.listdir("../data/raw"))

['SampleSuperstore.csv']

In [28]:
import os

print("Current working directory:")
print(os.getcwd())

Current working directory:
d:\downloads\Documents\Retail-Sales-Analytics\notebooks

In [29]:
import os

print("Project folders:")
print(os.listdir(".."))

Project folders:
['dashboard', 'data', 'images', 'models', 'notebooks', 'sql']

In [30]:
print(os.listdir("../data"))

['processed', 'raw']

In [31]:
import os

print("Current folder:")
print(os.getcwd())

print("\nParent folder contents:")
print(os.listdir(".."))

Current folder:
d:\downloads\Documents\Retail-Sales-Analytics\notebooks

Parent folder contents:
['dashboard', 'data', 'images', 'models', 'notebooks', 'sql']

In [32]:
import pandas as pd

df = pd.read_csv("../data/raw/SampleSuperstore.csv")

df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [33]:
# Check the number of rows and columns
print("Dataset Shape:", df.shape)

Dataset Shape: (9994, 13)

In [34]:
# Display all column names
df.columns

Index(['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [35]:
df.columns.tolist()

['Ship Mode',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Category',
 'Sub-Category',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [36]:
# Display information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   object
 1   Segment       9994 non-null   object
 2   Country       9994 non-null   object
 3   City          9994 non-null   object
 4   State         9994 non-null   object
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   object
 7   Category      9994 non-null   object
 8   Sub-Category  9994 non-null   object
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB

In [37]:
# Number of rows and columns
print(df.shape)

(9994, 13)

In [38]:
# Display the data type of each column
print(df.dtypes)

Ship Mode        object
Segment          object
Country          object
City             object
State            object
Postal Code       int64
Region           object
Category         object
Sub-Category     object
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
dtype: object

In [39]:
# Check missing values
print(df.isnull().sum())

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [40]:
# Check duplicate rows
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 17

In [41]:
# Summary statistics
df.describe()

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

In [42]:
# Unique values in Ship Mode
print(df["Ship Mode"].unique())

['Second Class' 'Standard Class' 'First Class' 'Same Day']

In [43]:
# Unique values in Segment
print(df["Segment"].unique())

['Consumer' 'Corporate' 'Home Office']

In [44]:
print(df["Category"].unique())

['Furniture' 'Office Supplies' 'Technology']

In [45]:
print(df["Region"].unique())

['South' 'West' 'Central' 'East']

In [46]:
# Remove leading/trailing spaces

df["Ship Mode"] = df["Ship Mode"].str.strip()
df["Segment"] = df["Segment"].str.strip()
df["Country"] = df["Country"].str.strip()
df["City"] = df["City"].str.strip()
df["State"] = df["State"].str.strip()
df["Region"] = df["Region"].str.strip()
df["Category"] = df["Category"].str.strip()
df["Sub-Category"] = df["Sub-Category"].str.strip()

In [47]:
# check for negative values
print("Minimum Sales:", df["Sales"].min())
print("Minimum Quantity:", df["Quantity"].min())
print("Minimum Discount:", df["Discount"].min())
print("Minimum Profit:", df["Profit"].min())

Minimum Sales: 0.444
Minimum Quantity: 1
Minimum Discount: 0.0
Minimum Profit: -6599.978

In [48]:
# Save cleaned dataset

df.to_csv("../data/processed/cleaned_superstore.csv", index=False)

print("✅ Cleaned dataset saved successfully!")

✅ Cleaned dataset saved successfully!

In [49]:
import os

print(os.listdir("../data/processed"))

['cleaned_superstore.csv']

In [50]:
git status

SyntaxError: invalid syntax (3528599804.py, line 1)